//
//  DummyPlanets.swift
//  iPlanet
//
//  Created by Arizal Pratama Tanu Andara on 18/08/21.
//

import UIKit
 
import UIKit
 
var planets: [Planet] = [
    Planet(photo: UIImage(named: "sun")!, name: "Sun", description: "The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma,[18][19] heated to incandescence by nuclear fusion reactions in its core, radiating the energy mainly as visible light, ultraviolet light, and infrared radiation. It is by far the most important source of energy for life on Earth. Its diameter is about 1.39 million kilometres (864,000 miles), or 109 times that of Earth. Its mass is about 330,000 times that of Earth; it accounts for about 99.86% of the total mass of the Solar System.[20] Roughly three quarters of the Sun's mass consists of hydrogen (~73%); the rest is mostly helium (~25%), with much smaller quantities of heavier elements, including oxygen, carbon, neon and iron."),
    Planet(photo: UIImage(named: "merkurius")!, name: "Merkurius", description: "Mercury is the smallest planet in the Solar System and the closest to the Sun. The period of revolution of this planet is the shortest of all the planets in the Solar System, which is 87.79 days. The planet is named after the god Mercury, the messenger of the gods in Roman mythology."),
    Planet(photo: UIImage(named: "venus")!, name: "Venus", description: "Venus is the second closest planet to the Sun after Mercury. This planet orbits the Sun for 224.7 Earth days. Venus has no natural satellites and is named after the goddess of love and beauty in Roman mythology. After the Moon, the planet is the brightest natural object in the night sky, with an apparent magnitude of 4.6 which is bright enough to cast shadows. Venus is an inferior planet with an elongation angle of 47.8°. The maximum brightness of the planet can be seen immediately before sunrise or after sunset, so it is called the Morning Star or Dusk Star."),
    Planet(photo: UIImage(named: "earth")!, name: "Earth", description: "Earth is the third planet from the Sun which is the densest planet and the fifth largest of the eight planets in the Solar System. Earth is also the largest of the four terrestrial planets of the Solar System. Earth is sometimes referred to as the world or the Blue Planet."),
    Planet(photo: UIImage(named: "mars")!, name: "Mars", description: "Mars is the fourth closest planet from the Sun. It is named after the Roman god of war, Mars. This planet is often dubbed the red planet because it looks reddish in color from afar. This is due to the presence of iron oxide on the surface of the planet Mars. Mars is a rocky planet with a thin atmosphere. On the surface of Mars are craters, volcanoes, valleys, deserts, and ice caps. Mars' rotation period and season cycles are similar to Earth's. On Mars stand Olympus Mons, the highest mountain in the Solar System, and Valles Marineris, the largest valley in the Solar System. In addition, in the northern hemisphere there is the Borealis basin which covers 40% of the Martian surface."),
    Planet(photo: UIImage(named: "jupiter")!, name: "Jupiter", description: "Jupiter is the fifth closest planet to the Sun after Mercury, Venus, Earth and Mars. This planet is also the largest planet in the Solar System. Jupiter is a gas giant with a mass one thousandth the mass of the Sun and two and a half times the mass of all the other planets in the Solar System. This planet and the other gas giants in the Solar System (namely Saturn, Uranus, and Neptune) are sometimes called the Jovian planets or outer planets. Jupiter has been known to astronomers since ancient times, and is associated with the mythologies and religious beliefs of many civilizations. The Romans named this planet after the god Jupiter in Roman mythology. When viewed from Earth, Jupiter's apparent magnitude can reach 2.94, which is bright enough to cast a shadow, and also makes it the third-brightest object in the night sky after the Moon and Venus, although Mars can rival Jupiter's brightness at times."),
    Planet(photo: UIImage(named: "saturnus")!, name: "Saturnus", description: "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth. It only has one-eighth the average density of Earth; however, with its larger volume, Saturn is over 95 times more massive. Saturn is named after the Roman god of wealth and agriculture; its astronomical symbol (♄) represents the god's sickle. The Romans named the seventh day of the week Saturday, Sāturni diēs (Saturn's Day) no later than the 2nd century for the planet Saturn."),
    Planet(photo: UIImage(named: "uranus")!, name: "Uranus", description: "Uranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus, who, according to Greek mythology, was the great-grandfather of Ares (Mars), grandfather of Zeus (Jupiter) and father of Cronus (Saturn). It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System. Uranus is similar in composition to Neptune, and both have bulk chemical compositions which differ from that of the larger gas giants Jupiter and Saturn. For this reason, scientists often classify Uranus and Neptune as ice giants to distinguish them from the other giant planets. Uranus's atmosphere is similar to Jupiter's and Saturn's in its primary composition of hydrogen and helium, but it contains more ices such as water, ammonia, and methane, along with traces of other hydrocarbons.[16] It has the coldest planetary atmosphere in the Solar System, with a minimum temperature of 49 K (−224 °C; −371 °F), and has a complex, layered cloud structure with water thought to make up the lowest clouds and methane the uppermost layer of clouds. The interior of Uranus is mainly composed of ices and rock."),
    Planet(photo: UIImage(named: "neptunus")!, name: "Neptunus", description: "Neptunus is a baseball and softball club in Rotterdam, the Netherlands. Following its 2014 championship season, the club signed a sponsorship contract for the 2015, 2016 and 2017 seasons with Curaçao and competes under the name Curaçao Neptunus. Baseball club Neptunus has a revenue of 1 million euros."),
    Planet(photo: UIImage(named: "pluto")!, name: "Pluto", description: "Pluto (minor planet designation: 134340 Pluto) is a dwarf planet in the Kuiper belt, a ring of bodies beyond the orbit of Neptune. It was the first and the largest Kuiper belt object to be discovered. After Pluto was discovered in 1930, it was declared to be the ninth planet from the Sun. Beginning in the 1990s, its status as a planet was questioned following the discovery of several objects of similar size in the Kuiper belt and the scattered disc, including the dwarf planet Eris. This led the International Astronomical Union (IAU) in 2006 to formally define the term planet—excluding Pluto and reclassifying it as a dwarf planet."),
    Planet(photo: UIImage(named: "nibiru")!, name: "Nibiru", description: "The Nibiru collision is the encounter of Earth with a large planet that is believed to occur at the beginning of the 21st century. Adherents of this event call the object approaching Earth as Planet X or Nibiru.")
]
